name: 'Run `swift test` on specific target'
description: 'Run Swift tests after switching directories'

inputs:
  directory:
    description: 'The directory to change to before running the test'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Swift
      shell: bash
      run: |
        if ! command -v swift &> /dev/null
        then
          echo "Swift not found. Installing Swift..."
          brew install swift
        else
          echo "Swift is already installed."
        fi
    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        swift package resolve
    - name: Purge Cache
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        swift package clean
    - name: Run Tests
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        swift test
