networks:
  monitoring:
  backend:

services:
  api-dev:
    volumes:
      - ./:/app/
      - /app/.build
      - api_build:/app/.build
    build:
      context: .
      dockerfile: ./DevDockerfile
      secrets:
        - GITHUB_SSH_AUTHENTICATION_TOKEN
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      temporal:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      promtail:
        condition: service_started
    environment:
      RUN_COMMAND: "serve --hostname 0.0.0.0"
      METRICS_PORT: "6834"
    ports:
      - "6886:8080"
    networks:
      - monitoring
      - backend

  temporal-worker:
    volumes:
      - ./:/app/
      - /app/.build
      - worker_build:/app/.build
    build:
      context: .
      dockerfile: ./DevDockerfile
      secrets:
        - GITHUB_SSH_AUTHENTICATION_TOKEN
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      temporal:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      promtail:
        condition: service_started
    environment:
      RUN_COMMAND: "temporal-worker"
      METRICS_PORT: "6835"
    networks:
      - monitoring
      - backend
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
    networks:
      - backend

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
      - PERSISTENCE_DIR=/tmp/localstack_data
    volumes:
      - "$PWD/infra/local/localstack/s3.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    networks:
      - backend
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
      - backend

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    image: grafana/grafana:latest
    volumes:
      - ./infra/compose-services-configurations/grafana:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./infra/compose-services-configurations/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring
  temporal:
    image: temporalio/temporal
    container_name: temporal
    command: ["server", "start-dev", "--ip", "0.0.0.0"]
    ports:
      - 8233:8233
    networks:
      - backend
volumes:
  postgres_data:
    driver: local
  api_build:
    driver: local
  worker_build:
    driver: local
  prom_data:

secrets:
  GITHUB_SSH_AUTHENTICATION_TOKEN:
    file: ./infra/docker-secrets/GITHUB_SSH_AUTHENTICATION_TOKEN
