# fly.toml app configuration file generated for backend-solitary-voice-65 on 2024-12-14T04:09:07-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automa-backend-workers-__FLY_ENVIRONMENT__'
primary_region = 'jnb'

[build]

[env]
RUN_COMMAND = "vapor-queues"

[[vm]]
memory = '1024mb'
cpu_kind = 'shared'
cpus = 2
min_machines_running = 1

[metrics]
port = 6834
path = "/metrics"
