# fly.toml app configuration file generated for backend-solitary-voice-65 on 2024-12-14T04:09:07-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automa-backend-__FLY_ENVIRONMENT__'
primary_region = 'jnb'

[build]

[env]
RUN_COMMAND = "serve --env production --hostname 0.0.0.0 --port 8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 4

[metrics]
port = 6834
path = "/metrics"
