name: 'Run `swift test` on specific target.'
description: 'Install Swift dependencies and run `swift test` on a specific target. // Always purges the cache before running the tests to ensure the latest code is tested.'

inputs:
  directory:
    description: 'The directory to change to before running the test'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        swift package resolve
    - name: Purge Cache
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        swift package clean
    - name: Run Tests
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        swift test
