apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://127.0.0.1:9090
    isDefault: false
    access: proxy
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://127.0.0.1:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://127.0.0.1:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
