name: Run `AutomaUIKit` tests

on:
  push:
    branches-ignore:
      - develop
      - release/staging
      - release/production

jobs:
  run:
    runs-on: [macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: "Switch -> Swift 6"
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"

      - name: Install NodeJS Dependencies
        run: |
          npm run prepare:action

      - name: Run Unit / Integration tests for AutomaUIKit
        uses: ./.github/actions/swift-test
        with:
          directory: 'App/AutomaUIKit'
