name: Run `AutomaBackend` Tests

on:
  pull_request:
    paths:
      - 'Backend/**/*.swift'

env:
  FLY_METRICS_TOKEN: ${{ secrets.TEST_FLY_METRICS_TOKEN }}
  PRIMARY_POSTGRES_URL: ${{ secrets.TEST_PRIMARY_POSTGRES_URL }}
  REGIONAL_POSTGRES_URL: ${{ secrets.TEST_REGIONAL_POSTGRES_URL }}
  ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
  JWT_ENCRYPTION_SECRET: ${{ secrets.TEST_JWT_ENCRYPTION_SECRET }}
  DISCORD_APP_EVENTS_URL: ${{ secrets.TEST_DISCORD_APP_EVENTS_URL }}
  OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
  TIGRIS_ACCESS_KEY_ID: ${{ secrets.TEST_TIGRIS_ACCESS_KEY_ID }}
  TIGRIS_ACCESS_KEY_SECRET: ${{ secrets.TEST_TIGRIS_ACCESS_KEY_SECRET }}
  TIGRIS_MEDIA_BUCKET_NAME: ${{ secrets.TEST_TIGRIS_MEDIA_BUCKET_NAME }}
  TIGRIS_BASE_URL: ${{ secrets.TEST_TIGRIS_BASE_URL }}
  LOG_LEVEL: ${{ secrets.TEST_LOG_LEVEL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.TEST_AWS_DEFAULT_REGION }}
  TWITTER_API_APP_KEY: ${{ secrets.TEST_TWITTER_API_APP_KEY }}
  TWITTER_API_APP_SECRET_KEY: ${{ secrets.TEST_TWITTER_API_APP_SECRET_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TEST_TWITTER_ACCESS_TOKEN }}
  TWITTER_SECRET_TOKEN: ${{ secrets.TEST_TWITTER_SECRET_TOKEN }}
  TEST_TWITTER_OAUTH_TOKEN_ID: ${{ secrets.TEST_TWITTER_OAUTH_TOKEN_ID }}
  TEST_TWITTER_USER_TOKEN_ID: ${{ secrets.TEST_TWITTER_USER_TOKEN_ID }}
  SEED_TWITTER_OAUTH_TOKEN: ${{ secrets.TEST_SEED_TWITTER_OAUTH_TOKEN }}
  SEED_TWITTER_OAUTH_TOKEN_SECRET: ${{ secrets.TEST_SEED_TWITTER_OAUTH_TOKEN_SECRET }}
  SEED_TWITTER_USER_ACCESS_TOKEN: ${{ secrets.TEST_SEED_TWITTER_USER_ACCESS_TOKEN }}
  SEED_TWITTER_USER_ACCESS_TOKEN_SECRET: ${{ secrets.TEST_SEED_TWITTER_USER_ACCESS_TOKEN_SECRET }}
  SEED_TWITTER_USER_ACCESS_TOKEN_VERIFIER: ${{ secrets.TEST_SEED_TWITTER_USER_ACCESS_TOKEN_VERIFIER }}
  TEST_CONTROLLERS_KEY: ${{ secrets.TEST_TEST_CONTROLLERS_KEY }}
  BACKEND_URL: ${{ secrets.TEST_BACKEND_URL }}
  PROMETHEUS_PORT: ${{ secrets.TEST_PROMETHEUS_PORT }}
  PROMETHEUS_BASE_URL: ${{ secrets.TEST_PROMETHEUS_BASE_URL }}
  AUTHENTICATION_CODE_RATE_LIMIT: ${{ secrets.TEST_AUTHENTICATION_CODE_RATE_LIMIT }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
           swift-version: "6.1"

      - uses: actions/cache@v4
        with:
          path: Backend/.build
          key: ${{ runner.os }}-backend-unittests-${{ hashFiles('**/Package.resolved') }}

      - name: Run Unit Tests
        uses: GetAutomaApp/opensource-actions/swifttesting@main
        with:
          compose: "false"
          working-directory: "Backend"
          swift_test_extra_args: "--filter '.*UnitTests.*'"

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
           swift-version: "6.1"

      - uses: actions/cache@v4
        with:
          path: Backend/.build
          key: ${{ runner.os }}-backend-integrationtests-${{ hashFiles('**/Package.resolved') }}

      - name: Run Integration Tests
        uses: GetAutomaApp/opensource-actions/swifttesting@main
        with:
          compose: "true"
          working-directory: "Backend"
          swift_test_extra_args: "--filter '.*IntegrationTests.*'"
          required_healthy_services_docker_compose: '["postgres", "localstack"]'
          compose_services_to_startup: '["postgres", "localstack"]'
          
