name: Run `AutomaUIKit` tests

on:
  push:
    branches-ignore:
      - develop
      - staging
      - prod

jobs:
  run:
    runs-on: [macOS]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Unit / Integration tests for AutomaUIKit
        uses: ./.github/actions/swift-test
        with:
          directory: 'App/AutomaUIKit'
