name: Run `AutomaCLI` tests

on:
  pull_request:
    paths:
      - "CLI/**/*.swift"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Restore Build Cache
        id: cache-build
        uses: actions/cache@v3
        with:
            key: cli-tests-cache-${{ hashFiles('CLI/Package.resolved') }}-${{ github.ref_name }}
            path: CLI/.build

      - name: Run SwiftTesting
        uses: GetAutomaApp/opensource-actions/swifttesting@main
        with:
          compose: "false"
          working-directory: "./CLI"
    env:
      FLY_METRICS_TOKEN: ${{ secrets.FLY_METRICS_TOKEN }}
