name: Run `AutomaCLI` tests 

on:
  pull_request:
    paths:
      - 'CLI/**'

jobs:
  swifttest:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Get Cache
        uses: actions/cache@v3
        id: cli-cache
        with:
          key: cli-cache-${{ hashFiles('CLI/Package.resolved') }}
          path: CLI/.build

      - name: Run SwiftTesting
        uses: GetAutomaApp/opensource-actions/swifttesting@5-implement-standardized-swift-test-action
        with:
          working-directory: './CLI'
          compose: 'true'
          compose-file: '../docker-compose.yml'
