name: Run `AutomaCLI` tests

on:
  push:
    branches-ignore:
      - develop
      - release/staging
      - release/production

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"

      - name: Install NodeJS Dependencies
        run: |
          npm install --ignore-scripts

      - name: Run Unit / Integration tests for AutomaCLI
        uses: ./.github/actions/swift-test
        with:
          directory: 'CLI'
