name: Run `AutomaApp(related)` Tests

on:
  pull_request:
    paths:
      - "App/AutomaApp/Core/**/*.swift"
      - "App/AutomaAppShared/**/*.swift"

jobs:
    automa-app-core-unit-and-integration-tests:
        runs-on: macos-15
        steps:
          - uses: actions/checkout@v4

          - uses: irgaly/xcode-cache@v1
            with:
              key: xcode-cache-deriveddata-${{ github.workflow }}
              restore-keys: xcode-cache-deriveddata-${{ github.workflow }}

          - name: Run Unit Tests
            uses: GetAutomaApp/opensource-actions/xctesting@9-implement-xcodebuild-testing-action
            with:
              working-directory: "./App/AutomaApp/"
              schema: "IOS"
              destination: "platform=iOS Simulator,name=iPhone 16,OS=18.0"
              testing-targets: "IOSIntegrationTests,IOSUnitTests"

    automa-app-core-ui-tests:
        runs-on: macos-15
        steps:
          - uses: actions/checkout@v4

          - uses: irgaly/xcode-cache@v1
            with:
              key: xcode-cache-deriveddata-${{ github.workflow }}
              restore-keys: xcode-cache-deriveddata-${{ github.workflow }}

          - name: Run Unit Tests
            uses: GetAutomaApp/opensource-actions/xctesting@9-implement-xcodebuild-testing-action
            with:
              working-directory: "./App/AutomaApp/"
              schema: "IOS"
              destination: "platform=iOS Simulator,name=iPhone 16,OS=18.0"
              testing-targets: "IOSUITests"