name: Code Review with ollama
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all
jobs:
  code_review:
    runs-on: [macos, self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ollama
        run: |
          which ollama || brew install ollama
          ollama ls | grep -c codellama || ollama pul codellama
        shell: bash
      - name: Code Review
        uses: ./.github/actions/ai-code-review
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_ADDRESS: "http://localhost:11434"
          exclude: "yarn.lock,dist/**,**/.swiftpm,**/.build/**,**/Pods/**"
