name: Fly Deploy To Staging

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run deploy:backend:staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PROD_API_KEY }}
          PRIMARY_POSTGRES_URL: ${{ secrets.POSTGRES_PROD_URL }}
          REGIONAL_POSTGRES_URL: ${{ secrets.POSTGRES_PROD_URL }}
