name: Fly Deploy To Sandbox

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy app
    runs-on: blacksmith-4vcpu-ubuntu-2404
    concurrency: deploy-group-sandbox
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.1"

      - name: Get Cache
        uses: useblacksmith/cache@v5
        id: backend-build
        with:
          key: deploy-cache-${{ hashFiles('Backend/Package.resolved') }}
          path: Backend/.build

      - name: Get CLI Cache
        uses: useblacksmith/cache@v5
        id: cli-build
        with:
          key: deploy-cache-${{ hashFiles('CLI/Package.resolved') }}
          path: CLI/.build

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          npm run deploy:backend:sandbox
          npm run deploy:worker:sandbox
          ls -a Backend
          ls -a CLI
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_SANDBOX_API_KEY }}
      FLY_METRICS_TOKEN: ${{ secrets.FLY_METRICS_TOKEN }}
