name: 'LLM Code Review'
on:
  workflow_dispatch:  # Changed to workflow_dispatch for manual trigger

jobs:
  llm-review:
    runs-on: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo "Running on branch: $GITHUB_REF"

      - name: Run LLM Code Review Action
        uses: ./.github/actions/llm-review-code
        with:
          llm-model: 'codegemma'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}