name: Swift

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "develop"
      - "staging"
      - "production"

jobs:
  build:
    runs-on: [self-hosted, macos]

    steps:
    - uses: actions/checkout@v4

    - name: Build the AutomaUIKit target
      run: swift build -v --package-path App/AutomaUIKit

    - name: Run tests (on non-develop, non-staging, non-production PRs)
      if: github.event_name == 'pull_request' && !contains(['develop', 'staging', 'production'], github.event.pull_request.base.ref)
      run: swift test -v --package-path App/AutomaUIKit
